### ISSUE TITLE
Wrong Account

### ISSUE THREAD

**Issue by Midwest-Jimmy** [Itz-Hyperz/RandyAccIDs#1]
778507122824577044 (9th account)
Sorry sir but my name is Jimmy I am a new user of discord I was asked to join your discord then you banned me and said I am randy I do not know what this randy dude did to you but I ensure you that is not me I do not know why you ask someone to join your discord then ban them either if we could talk about this you can reach me at Midwest Jimmy#2901 or by email at jimmymidwest@gmail.com
------------------------------------------------------------------------------------------------------------------------------------------------
~
Midwest Jimmy
Nice person

**Comment by Itz-Hyperz** [comment]
Hi "Midwest" Jimmy, I want you to know that I made no mistake with your ban, nor did I make a mistake with your account listing here. You show signs of Randy that nobody else meets (and I know a lot of people). Including not talking in VC, and constantly complimenting yourself. As well as the fact that you claim many things, however your discord account was created under a week ago. You also are not in MidwestRP, as I have connections with the owner of Midwest and he claims you are not in his server or community. You are speaking about RP as you spoke about CAD systems. I want you to know that I am very aware that you are Randy. Primarily because nobody "who knows nothing about development" would have a github, nor know what it is. You are Randy, and I want you to know that if you spam my Discord again, you will have officially broken the Cease & Desist letter you received (and I know you received it as Discord notified me of it.) STOP NOW, or I will be taking legal action, harassment is not a joke. Don't test me. Sincerely ~ Logan G.
